version: 2.1
orbs:
  flutter: circleci/flutter@1.1.0

jobs:
  build_flutter_apk:
    machine:
      image: android:2024.11.1
    resource_class: large
    steps:
      - checkout

      - flutter/install_sdk:
          version: 3.24.0

      - run:
          name: Flutter Doctor
          command: flutter doctor

      - run:
          name: Get Dependencies
          command: flutter pub get

      - run:
          name: Build APK
          command: flutter build apk --release

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: app-release.apk

  build_flutter_ipa:
    macos:
      xcode: 15.4.0
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout

      - flutter/install_sdk:
          version: 3.24.0

      - run:
          name: Flutter Doctor
          command: flutter doctor

      - run:
          name: Get Dependencies
          command: flutter pub get

      - run:
          name: Build iOS (No Codesign)
          command: flutter build ios --release --no-codesign

      - run:
          name: Create IPA from .app
          command: |
            mkdir -p build/ios/ipa/Payload
            cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/Runner.app
            cd build/ios/ipa
            zip -r app-unsigned.ipa Payload

      - store_artifacts:
          path: build/ios/ipa/app-unsigned.ipa
          destination: app-unsigned.ipa

workflows:
  build:
    jobs:
      - build_flutter_apk
      - build_flutter_ipa
