version: 2.1

orbs:
  flutter: circleci/flutter@1.1.0

jobs:
  build_flutter_apk:
    machine:
      image: android:2024.11.1
    resource_class: large
    steps:
      - checkout

      - flutter/install_sdk:
          version: 3.38.2

      - run:
          name: Flutter Doctor
          command: flutter doctor

      - run:
          name: Get Dependencies
          command: flutter pub get

      - run:
          name: Build APK
          command: flutter build apk --release

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: app-release.apk

workflows:
  build:
    jobs:
      - build_flutter_apk
